[general]
import=["/home/byk/.cache/wal/colors-alacritty.toml", "/home/byk/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_title = true
opacity = 0.8

[window.padding]
x = 25
y = 25
