source = ~/.config/hypr/colors.conf

# BACKGROUND
background {
    monitor = 
    blur_passes = 2
    path= $image
    contrast = 0.9
    brightness = 1.0
    vibrancy = 1.0
    vibrancy_darkness = 0.17
}

# GENERAL
general {
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor = 
    size = 300, 40
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $primary_fixed_dim
    inner_color = $primary
    font_color = $surface_container_low
    fade_on_empty = true
    placeholder_text = Enter password...
    hide_input = false
    position = 0, 150
    halign = center
    valign = bottom
}

image {
    monitor = 
    path = ~/Pictures/User_Profile_Pictures/User_(Windows_7).png
    size = 200
    rounding = 20

    border_color = $primary
    position = 0, 200

    halign = center
    valign = center
    
    shadow_passes = 2
    shadow_size = 3
    shadow_color = $secondary
    shadow_boost = 1.2
}

# Hour-time
label {
    monitor = 
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = $primary
    font_family = JetBrainsMono Bold
    font_size = 180
    position = -750, 150
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgb(255, 255, 255)
    shadow_boost = 0.6
}

# Minute-time
label {
    monitor = 
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = $secondary
    font_family = JetBrainsMono Bold
    font_size = 180
    position = -615, -50
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgb(255, 255, 255)
    shadow_boost = 0.6
}

# Terminal carrot.
label {
    monitor = 
    text = cmd[update:1000] echo -e "❯"
    color = rgb(95, 215, 0)
    font_family = Noto Sans Regular
    font_size = 120
    position = 500, -45
    halign = left
    valign = center
}
# Day-time
label {
    monitor = 
    text = cmd[update:1000] echo -e "$(date +"%A")"
    color = $secondary
    font_family = JetBrainsMono Bold
    font_size = 160
    position = 625, -50
    halign = left
    valign = center
    shadow_passes = 2
    shadow_size = 1
    shadow_color = rgb(255, 255, 255)
    shadow_boost = 0.6
}
