----------------------------------------------------------------------------------------
-- AUTOGENERATED HYPRLAND CONFIG.  						      --
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,--
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.                               --
----------------------------------------------------------------------------------------

require("binds")
require("colors")

-- # remove this line to remove the warning

-- # This is an example Hyprland config file.
-- # Refer to the wiki for more information.
-- # https://wiki.hyprland.org/Configuring/

-- # Please note not all available settings / options are set here.
-- # For a full list, see the wiki

-- # You can split this configuration into multiple files
-- # Create your files separately and then link them to this file like this:
-- # source = ~/.config/hypr/myColors.conf

----------------
--- MONITORS ---
----------------

-- # See https://wiki.hyprland.org/Configuring/Monitors/
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@120",
    position = "0x0",
    scale = "1",
    transform = 0,
    -- # supports_wide_color = 1
    -- # supports_hdr = 1
    -- # sdr_min_luminance = 0.0005
    -- # sdr_max_luminance = 250
    -- # bitdepth = 10
    -- # cm = hdr
})

-----------------
--- AUTOSTART ---
-----------------

-- # Autostart necessary processes (like notifications daemons, status bars, etc.)
-- # Or execute your favorite apps at launch like this:

hl.on("hyprland.start", function()
    -- # exec-once = $terminal
    -- # exec-once = nm-applet &
    hl.exec_cmd("waybar & awww-daemon & swaync")
    hl.exec_cmd("hyprpm -n")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    -- # exec-once = waybar & hyprpaper & firefox
end)

-----------------------------
--- ENVIRONMENT VARIABLES ---
-----------------------------

-- # See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("__GL_THREADED_OPTIMIZATIONS", "0")

---------------------
--- LOOK AND FEEL ---
---------------------

-- # Refer to https://wiki.hyprland.org/Configuring/Variables/
-- #layerrule = blur,waybar
-- # https://wiki.hyprland.org/Configuring/Variables/#general
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,

        border_size = 1,

        --	# https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        col = {
            active_border = on_primary_container,
            inactive_border = background,
        },
        --	# Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        --	# Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    --    # https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 10,
        rounding_power = 2,

        --	# Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = 0x1a1a1aee,
        },

        --	# https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,

            vibrancy = 0.1696,
        },
    },
    -- # https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = true,
    },
})
-- # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- # Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
-- # "Smart gaps" / "No gaps when only"
-- # uncomment all if you wish to use that.
-- # workspace = w[tv1], gapsout:0, gapsin:0
-- # workspace = f[1], gapsout:0, gapsin:0
-- # windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
-- # windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
-- # windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
-- # windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

-- # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- # You probably want this
    },
})
-- # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
hl.config({
    master = {
        new_status = "dwindle",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

-- # https://wiki.hyprland.org/Configuring/Variables/#misc
hl.config({
    misc = {
        force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})

-------------
--- INPUT ---
-------------

-- https://wiki.hypr.land/Configuring/Variables/#input
hl.config({
    input = {
        kb_layout = "us,il",
        kb_variant = "",
        kb_model = "",
        kb_options = "grp:alt_space_toggle",
        kb_rules = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures
-- gestures {
-- workspace_swipe = false
-- }

-- Example per-device config
-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

------------------------------
--- WINDOWS AND WORKSPACES ---
------------------------------

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule v1
-- windowrule = float, ^(kitty)$

-- Example windowrule v2
-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.
local supressMaximizeRule = hl.window_rule({
    name = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
hl.window_rule({
    -- Fix some dragging issues with XWayland
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name = "move-hyprland-run",

    match = { class = "hyprland-run" },

    move = "20 monitor_h-120",
    float = true,
})
